version: "3.8"
services:
  tata-core:
    build: ./docker/tata-core
    container_name: tata-core
    ports:
      - "5001:5001"
    environment:
      - SERVICE_NAME=Tata-CORE
    depends_on:
      - tata-memex
      - tata-zkp
      - postgres_core
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tata-network

  tata-memex:
    build: ./docker/tata-memex
    container_name: tata-memex
    ports:
      - "5002:5002"
    environment:
      - SERVICE_NAME=Tata-MEMEX
      - DB_HOST=mongodb
    depends_on:
      - mongodb_memex
    restart: always
    networks:
      - tata-network

  tata-zkp:
    build: ./docker/tata-zkp
    container_name: tata-zkp
    ports:
      - "5003:5003"
    environment:
      - SERVICE_NAME=Tata-ZKP
    depends_on:
      - postgres_zkp
      - redis_zkp
    restart: always
    networks:
      - tata-network

  tata-flow:
    build: ./docker/tata-flow
    container_name: tata-flow
    ports:
      - "5004:5004"
    environment:
      - SERVICE_NAME=Tata-FLOW
    depends_on:
      - redis_flow
    restart: always
    networks:
      - tata-network

  tata-moto:
    build: ./docker/tata-moto
    container_name: tata-moto
    ports:
      - "5005:5005"
    environment:
      - SERVICE_NAME=Tata-MOTO
    depends_on:
      - mysql_moto
    restart: always
    networks:
      - tata-network

  mongodb:
    image: mongo:latest
    container_name: tata-mongodb
    ports:
      - "27017:27017"
    networks:
      - tata-network
    volumes:
      - mongo-data:/data/db

  postgres_core:
    image: postgres:15
    environment:
      POSTGRES_USER: ${TATA_CORE_DB_USER}
      POSTGRES_PASSWORD: ${TATA_CORE_DB_PASSWORD}
      POSTGRES_DB: ${TATA_CORE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_core_data:/var/lib/postgresql/data
    networks:
      - tata-network

  redis_flow:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - tata-network

  mongodb_memex:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TATA_MEMEX_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${TATA_MEMEX_DB_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodb_memex_data:/data/db
    networks:
      - tata-network

  mysql_moto:
    image: mysql:8
    environment:
      MYSQL_ROOT_USER: ${TATA_MOTO_DB_USER}
      MYSQL_ROOT_PASSWORD: ${TATA_MOTO_DB_PASSWORD}
      MYSQL_DATABASE: ${TATA_MOTO_DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_moto_data:/var/lib/mysql
    networks:
      - tata-network

  postgres_zkp:
    image: postgres:15
    environment:
      POSTGRES_USER: ${TATA_ZKP_DB_USER}
      POSTGRES_PASSWORD: ${TATA_ZKP_DB_PASSWORD}
      POSTGRES_DB: ${TATA_ZKP_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_zkp_data:/var/lib/postgresql/data
    networks:
      - tata-network

  redis_zkp:
      image: redis:7
      ports:
        - "6380:6379"
      networks:
        - tata-network

networks:
  tata-network:
    driver: bridge

volumes:
  mongo-data:
  postgres_core_data:
  mongodb_memex_data:
  mysql_moto_data:
  postgres_zkp_data:
